const ADD_TO_BASKET = "ADD_TO_BASKET"
const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT"
const SUBTRACT_FROM_BASKET = "SUBTRACT_FROM_BASKET"

export {
  ADD_TO_BASKET,
  INCREASE_PRODUCT_COUNT,
  SUBTRACT_FROM_BASKET
}
