const GO_TO_PAGE = "GO_TO_PAGE"
const GET_PRODUCTS = "GET_PRODUCTS"
const SORT_PRODUCTS = "SORT_PRODUCTS"
const MIGRATE_MANUFACTURERS = "MIGRATE_MANUFACTURERS"
const FILTER_PRODUCTS = "FILTER_PRODUCTS"

export {
  GET_PRODUCTS,
  SORT_PRODUCTS,
  FILTER_PRODUCTS,
  MIGRATE_MANUFACTURERS,
  GO_TO_PAGE
}
